#!/bin/sh

#  StoryboardControllers.sh
#  Viva1
#
#  Created by vishwender on 1/18/18.
#  Copyright © 2018 viva. All rights reserved.

echo "-------------------- StoryboardControllers.sh started --------------------"

commonLibSource="$SRCROOT/Viva1/Scripts/commonLib.sh"

projectDir="$SRCROOT/Viva1"
outputFile="$SRCROOT/Viva1/Constants/StoryboardControllers.swift"

rm StoryboardEnum.txt 2>/dev/null
rm StoryboarVcVariable.txt 2>/dev/null
rm StoryboardInstance.txt 2>/dev/null

# output file structure creation start
touch StoryboardEnum.txt
touch StoryboarVcVariable.txt
touch StoryboardInstance.txt

echo "enum Storyboard : String {" >> StoryboardEnum.txt
echo "enum StoryboardViewController: String {" >> StoryboarVcVariable.txt
echo "    var storyboard: Storyboard {" >> StoryboardInstance.txt
echo "        switch self {" >> StoryboardInstance.txt

find $projectDir -type f -name *.storyboard -print0 | while IFS= read -r -d $'\0' line; do
fullname=`ls -1 "$line"`
storyboardName=`basename "$fullname" .storyboard`
enumName=`source $commonLibSource; firstCharacterToLower $storyboardName`
echo "    case $enumName = \"$storyboardName\"" >> StoryboardEnum.txt
storyboardIdentifierLine=`grep -n "storyboardIdentifier" "$fullname"`
for storyboardIdentifierPattern in `echo "$storyboardIdentifierLine" | sed 's/.*\(storyboardIdentifier="[a-zA-Z0-9]*"\).*/\1/'`; do
storyboardIdentifier=`echo $storyboardIdentifierPattern | sed 's/.*\("[a-zA-Z0-9]*"\).*/\1/'`
storyboardIdentifier=`echo $storyboardIdentifier | sed -e 's/^"//' -e 's/"$//'`
storyboardIdentifierVariable=`source $commonLibSource; firstCharacterToLower $storyboardIdentifier`

echo "    case $storyboardIdentifierVariable = \"$storyboardIdentifier\"" >> StoryboarVcVariable.txt
echo "        case .$storyboardIdentifierVariable:" >> StoryboardInstance.txt
echo "            return .$enumName" >> StoryboardInstance.txt

done

done

echo "" >> StoryboardEnum.txt
echo "    var instance : UIStoryboard {" >> StoryboardEnum.txt
echo "        return UIStoryboard(name: self.rawValue, bundle: Bundle.main)" >> StoryboardEnum.txt
echo "    }" >> StoryboardEnum.txt
echo "}" >> StoryboardEnum.txt
echo "" >> StoryboardEnum.txt

echo "        }" >> StoryboardInstance.txt
echo "    }" >> StoryboardInstance.txt

cat StoryboardInstance.txt >> StoryboarVcVariable.txt

echo "" >> StoryboarVcVariable.txt
echo "    var instance: UIViewController {" >> StoryboarVcVariable.txt
echo "        return self.storyboard.instance.instantiateViewController(withIdentifier: self.rawValue)" >> StoryboarVcVariable.txt
echo "    }" >> StoryboarVcVariable.txt
echo "}" >> StoryboarVcVariable.txt

cat StoryboarVcVariable.txt >> StoryboardEnum.txt

rm headerFile.txt 2>/dev/null
touch headerFile.txt
echo "//" >> headerFile.txt
echo "//  Constants.storyboards.swift" >> headerFile.txt
echo "//  Viva" >> headerFile.txt
echo "//" >> headerFile.txt
echo "//  Created by vishwender on 1/22/18." >> headerFile.txt
echo "//  Copyright © 2018 viva. All rights reserved." >> headerFile.txt
echo "//" >> headerFile.txt
echo "// This file is autogenerated, do not edit here" >> headerFile.txt
echo "" >> headerFile.txt
echo "import Foundation" >> headerFile.txt
echo "import UIKit" >> headerFile.txt
echo "" >> headerFile.txt

cat StoryboardEnum.txt >> headerFile.txt

rm $outputFile
mv headerFile.txt $outputFile

rm StoryboardEnum.txt 2>/dev/null
rm StoryboarVcVariable.txt 2>/dev/null
rm StoryboardInstance.txt 2>/dev/null
rm headerFile.txt 2>/dev/null

echo "-------------------- StoryboardControllers.sh stopped --------------------"
